### ISSUE TITLE
New release/version in pypi/conda-forge?

### ISSUE THREAD

**Issue by mattvw** [Valassis-Digital-Media/conda-mirror#76]
Any way we could get a new release of conda-mirror on GitHub and the new version uploaded to PyPi and/or conda-forge? (I'd prefer PyPi myself!)

There's been a bunch of very nice/useful commits to master since the latest 0.7.4 release on September 19, 2017 (including some really nice new options to the package)...

It'd be much easier to install the latest from PyPi or conda-forge rather than pulling down the master source!

Seems like there's a nice release.sh script to make making new releases much easier too!

Really great package!!

Thanks!!

**Comment by parente** [comment]
I'm going through the open PRs now and will cut a release after updating the README and CHANGELOG.

**Comment by parente** [comment]
Tacking TODOs in #77.

**Comment by mattvw** [comment]
Thank you very much @parente!!
